config/routes.rb
Rails.application.routes.draw do
  resources :maps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:nome, :matricula, :cpf, :bairro, :ativo, :dor_garganta, :tosse, :febre, :dif_respirar, :nenhum_sint)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmapsRailsExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= yield %>
   
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.number_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.number_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.number_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :ativo %>
    <%= form.check_box :ativo %>
  </div>

  <div class="field">
    <%= form.label :dor_garganta %>
    <%= form.check_box :dor_garganta %>
  </div>

  <div class="field">
    <%= form.label :tosse %>
    <%= form.check_box :tosse %>
  </div>

  <div class="field">
    <%= form.label :febre %>
    <%= form.check_box :febre %>
  </div>

  <div class="field">
    <%= form.label :dif_respirar %>
    <%= form.check_box :dif_respirar %>
  </div>

  <div class="field">
    <%= form.label :nenhum_sint %>
    <%= form.check_box :nenhum_sint %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(-3.71839, -38.5434)
    });
    </script>
    
<% end %>

<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Cpf</th>
      <th>Bairro</th>
      <th>Ativo</th>
      <th>Dor garganta</th>
      <th>Tosse</th>
      <th>Febre</th>
      <th>Dif respirar</th>
      <th>Nenhum sint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>

    <script>
var GID_BANCO= (<%= map.bairro %>);
console.log(GID_BANCO)
</script>

      <tr>
        <td><%= map.nome %></td>
        <td><%= map.matricula %></td>
        <td><%= map.cpf %></td>
        <td><%= map.bairro %></td>
        <td><%= map.ativo %></td>
        <td><%= map.dor_garganta %></td>
        <td><%= map.tosse %></td>
        <td><%= map.febre %></td>
        <td><%= map.dif_respirar %></td>
        <td><%= map.nenhum_sint %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

<p>
    <div id="map"></div>
</p>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(-3.71839, -38.5434)
    });
    </script>
    
<% end %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @map.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @map.matricula %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @map.cpf %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @map.bairro %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @map.ativo %>
</p>

<p>
  <strong>Dor garganta:</strong>
  <%= @map.dor_garganta %>
</p>

<p>
  <strong>Tosse:</strong>
  <%= @map.tosse %>
</p>

<p>
  <strong>Febre:</strong>
  <%= @map.febre %>
</p>

<p>
  <strong>Dif respirar:</strong>
  <%= @map.dif_respirar %>
</p>

<p>
  <strong>Nenhum sint:</strong>
  <%= @map.nenhum_sint %>
</p>

<p>
    <div id="map"></div>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>


<script>

var GID_BANCO = (<%= @map.bairro %>);
    

</script>